# Generated by Django 4.1.4 on 2022-12-23 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 0, 0)),
        ),
    ]
