# Generated by Django 4.1.3 on 2023-01-01 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200, unique=True)),
                ('max_age', models.IntegerField()),
                ('min_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassOfSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.CharField(max_length=10)),
                ('max_number', models.IntegerField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.age')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('approved_mark', models.FloatField(default=5.0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.age')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('1', 'Nam'), ('0', 'Nữ')], default='1', max_length=1)),
                ('address', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('classOfSchool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.classofschool')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markFifteen', models.FloatField(blank=True, null=True)),
                ('markOne', models.FloatField(blank=True, null=True)),
                ('markFinal', models.FloatField(blank=True, null=True)),
                ('semester_mark', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
                ('subjects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subject')),
            ],
        ),
    ]
